name: Release

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name of the release"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: Update package.json
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ github.event.inputs.name }}\"/" ./package.json

      - name: Prepare release
        shell: bash
        run: |
          pnpm pack

      - name: Commit version change
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add ./package.json
          git commit -m "release: v${{ github.event.inputs.name }}"
          git tag "v${{ github.event.inputs.name }}"

      - name: Publish to npm
        run: |
          pnpm publish --access public

      - name: Push Tag
        run: |
          git push
